### ISSUE TITLE
Anonymous User is able to delete reviews

### ISSUE THREAD

**Issue by eeftychiou** [mehmetbajin/gt-course-surveys#1]
Anonymous users should only be able to post reviews and not modify or delete existing reviews

**Comment by mehmetbajin** [comment]
Good call. Since we have the checkbox to flag yourself as "wanting to remain anonymous" in the My Account page, there is no longer a need for anonymous login. I removed anonymous login, and now, a user can edit/remove only reviews he/she has authored.
