### ISSUE TITLE
think about limiting the review length

### ISSUE THREAD

**Issue by cmeury** [mehmetbajin/gt-course-surveys#10]
Having (seemingly) unlimited review length might cause reviews to be more elaborate than they would need to be. Over time, it will get difficult to get an overview over the class since there will be a LOT of reviews, and potentially long ones. This ties in with #8 - long term, it would to help to have more "summarizing" data points than individual longer comments.

About review length, maybe a maximum of 2000 characters would be enough, adding an indiciator of characters left in the input field. What do you and others think about it?

**Comment by mehmetbajin** [comment]
I'd like to monitor the trends before implementing any limits.

The view that displays the reviews can be updated to truncate after a certain threshold, requiring the user to click to "view more".

I like the idea of an indicator to warn the user of the length of the review.

**Comment by mehmetbajin** [comment]
Resolved with version 2. Now limiting to 1000 characters.
