### ISSUE TITLE
allow exporting of the data

### ISSUE THREAD

**Issue by cmeury** [mehmetbajin/gt-course-surveys#11]
Concerns were raised on Google+ about hiding the community's data behind a closed database. We might need to think about adding an export functionality to make sure we can periodically backup the data in case of any emergency. Maybe a simple CSV exporter would be sufficient already.

Relevant part of original comment: "not [..] comfortable with taking our shared spreadsheet and putting it behind a locked database. The spreadsheet was a shared resource, everyone could make a copy of it, download it and modify it anonymously. Your site [..] the dataset is not available."

**Comment by mehmetbajin** [comment]
The data is not locked down. You can access it through the following RESTful API:

https://gt-surveyor.firebaseio.com/reviews.json
https://gt-surveyor.firebaseio.com/grades.json

It makes sense to add these APIs to the FAQ.

**Comment by mehmetbajin** [comment]
Resolved with version 2.
