### ISSUE TITLE
grade data combines OMS & resident sections

### ISSUE THREAD

**Issue by cgearhart** [mehmetbajin/gt-course-surveys#15]
The grade data mixes results from OMS sections with on-campus sections, which could lead to incorrect expectations among OMS students using the tool. As a specific example, in Fall 2014, CS-6505A (on campus) saw 44/76 A's, while CS-6505-O01 (OMS) saw 49/137 A's (adjusted for withdrawals); the dataset used in this tool shows a total of 93 A's from Fall '14. Mixing data with a higher pass rate from the resident section with the results of the OMS section inflates expectations among future OMS students.

**Comment by cpcahil** [comment]
Chris, what is the source of your data?   I don't see a way to isolate grades between different sections on http://www.irp.gatech.edu/reports/grade_distributionsmry.php which is the source of the grade reports. 

Perhaps your source could also be used to break out the different sections of 8803.

**Comment by cgearhart** [comment]
If you click on "CS" in the left-most column it will open a detailed view for the associated term that breaks out all of the sections. Then you can simply look for courses with "O01", "O02", and so on. It will also allow you to split the 8803 sections.

**Comment by cpcahil** [comment]
ahh...  Thanks... I have to say that is not the most obvious option

**Comment by mehmetbajin** [comment]
Will be fixed along with the Fall 2015 grade import once Fall 2015 grades are available.

**Comment by mehmetbajin** [comment]
Fixed. Now, the grade data includes data from only online sections going back to Spring 2014.

**Comment by cgearhart** [comment]
I'm not sure whether it was intentional or not, but it looks like the current data set only uses a single semester for each class. I have a combined dataset for all OMS semesters in JSON format - although I kept the O01 suffix on all keys - at: https://gist.github.com/cgearhart/8d38b212f8db8bd67868bcc04d037da6

**Comment by mehmetbajin** [comment]
What made you reach that conclusion? I made sure to include every OMSCS section going back to Fall 2014.

**Comment by cgearhart** [comment]
The grade counts differ significantly and the data in firebase for each course exactly matches the data for only a single semester of each class. Taking a single course as an example, consider CS6250, which has run every semester in OMS since Spring 2014. The data on firebase linked from the course survey at https://gt-surveyor.firebaseio.com/grades.json shows "6250":{"a":97,"b":5,"c":1,"d":0,"f":2,"i":0,"s":0,"total":117,"u":0,"v":0,"w":12} which exactly matches the counts reported on IRP for Spring 2014, while the cumulative data that I compiled from IRP for all semesters shows "6250-01":{"a":1184,"b":268,"c":40,"d":10,"f":36,"s":0,"u":0,"i":0,"w":202,"v":0,"total":1740}.

**Comment by mehmetbajin** [comment]
Great catch. Fixed.

**Comment by mehmetbajin** [comment]
For reference, here is the data source:

```

# COLUMNS
# A B C D F S U I W V TOTAL

# FALL 2015

6035: 126   97  6   0   0   0   0   0   16  0   245
6210: 41    23  6   0   4   0   0   0   50  0   124
6220: 16    23  10  4   2   0   0   4   71  0   130
6242:
6250: 175   91  14  4   12  0   0   0   48  0   344
6262:
6290: 27    24  6   3   6   0   0   0   44  0   110
6300: 211   69  12  10  4   0   0   0   46  0   352
6310: 130   37  8   0   5   0   0   0   84  0   264
6340:
6400:
6440: 164   8   0   0   0   0   0   0   12  0   184
6460: 86    5   0   1   1   0   0   1   7   0   101
6465:
6475: 72    39  4   2   1   0   1   0   23  0   142
6476: 70    52  19  5   1   0   0   0   54  0   201
6505: 21    52  36  8   14  0   0   0   142 0   273
6601:
7637: 145   21  9   4   4   0   0   0   49  0   232
7641: 143   47  5   6   6   0   0   0   152 0   359
7646: 293   46  11  4   12  0   0   0   18  0   384
8803-001: 134   14  4   1   2   0   0   0   6   0   161
8803-002: 90    43  11  2   8   0   0   1   95  0   250
8803-003: 69    17  3   0   2   0   0   0   26  0   117
8803-004:
8803-005:
8803-006:
8803-BDHI:

# SUMMER 2015

6035:
6210:
6220:
6242:
6250: 250   29  3   4   12  0   0   0   46  0   344
6262:
6290:
6300: 143   40  13  4   9   0   0   0   23  0   232
6310:
6340:
6400:
6440:
6460:
6465:
6475: 81    34  9   1   0   0   0   0   13  0   138
6476:
6505:
6601:
7637: 215   51  6   3   12  0   0   0   83  0   370
7641:
7646:
8803-001: 151   15  4   0   2   0   0   0   10  0   182
8803-002: 81    49  5   5   7   0   0   0   98  0   245
8803-003:
8803-004:
8803-005:
8803-006:
8803-BDHI:

# SPRING 2015

6035:
6210: 52    23  3   3   3   1   0   1   92  0   178
6220:
6242:
6250: 344   96  5   0   4   0   0   0   45  0   494
6262:
6290: 26    33  13  7   10  0   0   0   72  0   161
6300: 241   41  10  4   1   0   0   0   24  0   321
6310: 88    44  6   0   4   0   0   0   63  0   205
6340:
6400:
6440: 159   23  1   0   0   0   0   1   10  0   194
6460:
6465:
6475: 115   22  10  3   4   0   0   0   30  0   184
6476: 114   24  5   1   7   0   0   0   36  0   187
6505: 56    37  15  9   10  0   1   2   107 0   237
6601:
7637: 165   33  9   2   3   0   0   0   55  0   267
7641: 124   38  9   6   1   0   0   0   126 0   304
7646:
8803-001: 134   21  3   3   5   0   0   1   26  0   193
8803-002: 106   68  7   1   10  0   0   0   129 0   321
8803-003:
8803-004:
8803-005:
8803-006:
8803-BDHI:

# FALL 2014, 4495 = 6476

6035:
6210: 24    35  6   4   6   0   0   0   78  0   153
6220:
6242:
6250: 182   29  8   0   4   0   0   0   33  0   256
6262:
6290: 19    14  13  1   3   0   0   0   60  0   110
6300: 163   43  13  6   8   0   0   0   25  0   258
6310: 82    53  4   0   6   0   0   0   50  0   195
6340:
6400:
6440: 70    27  2   0   1   0   0   1   27  0   128
6460:
6465:
6475:
6476:
6505: 49    44  24  10  9   0   1   0   83  0   220
6601:
7637: 138   25  4   0   3   0   0   0   26  0   196
7641: 84    48  4   12  4   0   0   0   97  0   249
7646:
8803-001: 43    7   0   2   3   0   0   0   8   0   63
8803-002:
8803-003:
8803-004:
8803-005:
8803-006:
8803-BDHI:

# SUMMER 2014

6035:
6210:
6220:
6242:
6250: 136   18  9   2   2   0   0   0   18  0   185
6262:
6290:
6300: 174   12  3   3   7   0   0   0   7   0   206
6310:
6340:
6400:
6440:
6460:
6465:
6475:
6476:
6505:
6601:
7637:
7641:
7646:
8803-001: 78    16  3   2   6   0   0   0   4   0   109
8803-002:
8803-003:
8803-004:
8803-005:
8803-006:
8803-BDHI:

# SPRING 2014

6035:
6210: 36    7   0   2   0   0   0   0   60  0   105
6220:
6242:
6250: 97    5   1   0   2   0   0   0   12  0   117
6262:
6290:
6300: 85    18  8   3   8   0   0   0   8   0   130
6310:
6340:
6400:
6440:
6460:
6465:
6475:
6476:
6505:
6601:
7637:
7641: 58    25  2   3   1   0   0   0   64  0   153
7646:
8803-001: 41    4   1   6   5   0   0   0   14  0   71
8803-002:
8803-003:
8803-004:
8803-005:
8803-006:
8803-BDHI:
```
