### ISSUE TITLE
login form does not work with password manager (KeePass)

### ISSUE THREAD

**Issue by cmeury** [mehmetbajin/gt-course-surveys#18]
### Steps to reproduce
1. Go to https://gt-course-surveys.herokuapp.com/#/login
2. Let KeePass (via KeeFox browser plugin) fill out the form automatically
### Observation
- Both username and password are filled in, but the Login button is disabled.
### Expectation
- The Login button is enabled.
### Workaround
- Entering any character and pressing backspace (to not make the credentials incorrect) will "unlock" the login button.

**Comment by mehmetbajin** [comment]
Setting an interval to trigger the controls may do the trick:

http://stackoverflow.com/questions/31288826/keepass-and-angularjs-login-form-doesnt-trigger-validation

**Comment by mehmetbajin** [comment]
Verified fix with Dashlane. Please reopen if issue persists.
