### ISSUE TITLE
Course titles in the sidebar are abbreviated by cutting off whole words

### ISSUE THREAD

**Issue by cmeury** [mehmetbajin/gt-course-surveys#20]
### Observation
- Course titles are abbreviated like this: "CS 6601 Artifical Intelligence" -> "CS 6601 Artificial"
### Expectation
- I can imagine different ways of improving this:
  - Abbreviate with 3 dots at some point
  - Removing the department to save space
  - Define abbreviations for all courses and displays Deparment-Number-Abbreviation (we could also list departments on a separate page - added benefit of everyone hopefully using the same abbreviations)

**Comment by mehmetbajin** [comment]
I removed department and introduced ellipses.
