### ISSUE TITLE
8803 - BDH missing

### ISSUE THREAD

**Issue by carl-heller** [mehmetbajin/gt-course-surveys#22]
This course only shows up in the all reviews section, but not in the course reviews section.

**Comment by mehmetbajin** [comment]
Looks like it's in the DOM but is just not visible. Likely a CSS issue.

**Comment by mehmetbajin** [comment]
There was a max-height of 1300px on the sidebar course buttons container inherited from the Triangular framework. I've removed it and the buttons display correctly now.
