### ISSUE TITLE
Add course milestone/version change to course numbers

### ISSUE THREAD

**Issue by benlten** [mehmetbajin/gt-course-surveys#38]
Some courses have evolved or are being rebuilt, revamped, changed, enhanced by the department. 
Adding a way to filter by course version would be good, since many of the courses are no longer "easy" or hard, or even the same as the V1.0 that the AT&T students have gone through.

**Comment by mehmetbajin** [comment]
Current filtering functionality allows filtering by semester. Would that work?

Otherwise, is there a good resource for identifying versions of courses?

**Comment by benlten** [comment]
That's a possibility. The department would know when the course was changed, as is the case for CCA, which has undergone several iterations - and is ultimately end of lifed right now. 

In the case of OMSCS, filtering by professor might not be perfect since the videos are pre-recorded even if another professor did the piazza part.
