### ISSUE TITLE
Login with Github causes 500 error

### ISSUE THREAD

**Issue by burlesona** [mehmetbajin/gt-course-surveys#39]
Looks like the app gets into some kind of infinite loop after you login with Github then try to navigate off the profile page. If you refresh the page after getting the 500 error the app just hangs at the loading screen. On Chrome there's no error in the console. In Safari it gives an error saying pushState tried to fire too many times, and the URL bar flickers `/reviews`.

**Comment by mehmetbajin** [comment]
@burlesona This may be caused by an outdated client. In Chrome, in Developer Tools > Network, uncheck `Disable cache` and reload the page. Then, attempt reproducing. Are you successful?

**Comment by burlesona** [comment]
I get the same behavior with cache disabled, incognito, and alternate devices.

**Comment by mehmetbajin** [comment]
I identified the root cause (not having a specialization defined) and deployed a hotfix. Please clear your browser cache and revisit the page. Thanks!
