### ISSUE TITLE
highlight courses relevant to specialization

### ISSUE THREAD

**Issue by mehmetbajin** [mehmetbajin/gt-course-surveys#4]

**Comment by dbur** [comment]
+1. more granular indicators for within each specialization may be useful as well. ie ML specialization has 3 groups of courses requiring 1 course/1 course/3 courses

**Comment by jeffeharris** [comment]
+1

**Comment by mehmetbajin** [comment]
Done & deployed. Two new icons to indicate core/elective courses relevant to spec.
