### ISSUE TITLE
Grade distribution for Computer Vision is missing

### ISSUE THREAD

**Issue by pullmonkey** [mehmetbajin/gt-course-surveys#6]
Hello -  

Thank you for this application, very useful and very informative!

Computer Vision (CS6476) was formerly CS4495 (see http://www.omscs.gatech.edu/cs-6476-computer-vision/) and that data does exist in your cs.txt.  Similarly, CS6476 was incorrectly labelled as CS7495 on the OMSCS courses/program page for a while.  CS7495 also exists in your cs.txt file.  But CS7495 may be for an actual other course.

Hope this helps

**Comment by mehmetbajin** [comment]
I added 6476.

I am not going to risk adding false data with 7495.
