### ISSUE TITLE
Adding Grades?

### ISSUE THREAD

**Issue by filmo** [mehmetbajin/gt-course-surveys#7]
I don't see an obvious area to add my grade to a particular class.  Did I miss it somewhere?

**Comment by mehmetbajin** [comment]
Grades are not entered by students. Instead, I scrape them from the following url after every semester:

http://www.irp.gatech.edu/reports/grade_distributionsmry.php

**Comment by cmeury** [comment]
I would consider adding this information on the grades page, as I spent a couple of minutes frantically clicking through the tool trying to find the input field :)
